# Site settings
title: Hack and Tell @Iași
description: >
  H&&T is a show and tell style meetup for hackers!
  Events are structured such that 8—10 hackers give 5 minute long
  presentations on something they built, and then respond to Q&A
  for 5 more minutes.

baseurl: ""
url: "https://iasi.hackandtell.ro"

author:
  fullname: Hack and Tell @Iași
  github: https://github.com/hackandtell-ro/

# Build settings
markdown: kramdown